name: Deploy to Development

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Deploy to the server
        run: echo Hello, world!
        env:
          API_KEY: ${{ secrets.API_KEY }}
          FE_URL: ${{  vars.FE_APP_URL }}
